language: cpp
dist: trusty
sudo: required

before_install:
    - sudo apt-get update
    - sudo apt-get upgrade

env:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release
    - BUILD_TYPE=RelWithDebInfo
    - BUILD_TYPE=RelWithDebInfo

compiler:
    - gcc
    - clang

before_script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..

script:
    - make -j4
